### ISSUE TITLE
Request for more details of annotation process

### ISSUE THREAD

**Issue by MajmasterHYT** [PinataFarms/DAD-3DHeads#2]
Thanks for your sharing!
We'll appreciate it if you could show us more details of the whole process of annotation(how to build a preliminary mesh before labeling and which modifier is used to optimise the mesh with blender).

**Comment by t-martyniuk** [comment]
Thanks for your interest!

Please see Section 3.1 of the main paper and Supplementary A.3 for more details on the annotation process. You can also check the video here: https://www.pinatafarm.com/research/dad-3dheads/dataset

When the annotator pins a point on the model surface, the non-linear least squares optimization runs over the shape+expression parameters of the model, so that the discrepancy between the projections of the points on the model surface that were pinned and the pixels that those points were pinned to is the smallest.
