### ISSUE TITLE
How to generate 'rotation_matrix' and '7_landmarks_3d' for all validation/test images

### ISSUE THREAD

**Issue by jiangjin1246** [PinataFarms/DAD-3DHeads#22]
Thank you very much for your excellent work! 
There are some trouble when I use the 'dad_3dheads_benchmark'. Could you please share the way to generate 'rotation_matrix' and '7_landmarks_3d' for all validation/test images? 
Thanks again!

**Comment by t-martyniuk** [comment]
- As per 'rotation_matrix' of your model - it depends on your method. The rotation matrix in our method is obtained from the FLAME parameters - we refer you to `model_training/model/flame.py`, `rotation_mat_from_flame_params` function. 
- As per '7_landmarks_3d' - we refer you to the RingNet(https://ringnet.is.tue.mpg.de) and NoW Benchmark(https://github.com/soubhiksanyal/now_evaluation), as it is mentioned in our `README.md`.

In order to evaluate your submission on the test set, submit your prediction via email: dad3dheads@gmail.com.

**Comment by jiangjin1246** [comment]
> * As per 'rotation_matrix' of your model - it depends on your method. The rotation matrix in our method is obtained from the FLAME parameters - we refer you to `model_training/model/flame.py`, `rotation_mat_from_flame_params` function.
> * As per '7_landmarks_3d' - we refer you to the RingNet(https://ringnet.is.tue.mpg.de) and NoW Benchmark(https://github.com/soubhiksanyal/now_evaluation), as it is mentioned in our `README.md`.
> 
> In order to evaluate your submission on the test set, submit your prediction via email: [dad3dheads@gmail.com](mailto:dad3dheads@gmail.com).

Thanks for your kind reply!
 I also generate the [5023, 3] mesh_vertices like DAD-3DNet, can I obtain the '7_landmarks_3d' using the function in `DAD-3DHeads/dad_3dheads_benchmark/utils.py` ("full_gt_lmks = get_68_landmarks(mesh_vertices)" and "svn_lmks = get_7_landmarks_from_68(full_gt_lmks)")

**Comment by t-martyniuk** [comment]
yes, the functions `get_68_landmarks` get 68 vertices from 5023 vertices, and `get_7_landmarks_from_68` get 7 from 68, respectively.
